### PR TITLE
add ability to use more rule var sets

### PR DESCRIPTION
**Pull request by cryptolukas**
Hey,

I added the fuction to generate ufw rules from group_vars, hosts_vars and directly as well.
I hope you like my pull request, I need such a function to generate more complex role-base ufw rulesets.

### CODE REVIEW

**Comment by tersmitten** [comment]
I'm not sure that I understand your use-case. Can you share an example?

**Comment by cryptolukas** [comment]
Sorry for my delayed answer. 
At the moment The role is unable to handle multi level ufw rules.

A.e.
* ufw rules from group_vars
* ufw rules from host_vars
* ufw rules from roles

**Comment by starcraft66** [comment]
@cryptolukas This kind-of goes against the way ansible handles variable files. I think what you want to do in this case is build an array with all of your rules by merging different arrays defined in different variable files.
See: https://stackoverflow.com/questions/24090177/how-to-merge-yaml-arrays

**Comment by tersmitten** [comment]
Closing due to inactivity

**Pull request closed without merging**
